#!/usr/bin/env bash
#
# Assert that packages/kysely/src/schema.ts still matches what the
# migrations produce.
#
# Why this exists: schema.ts is generated by kysely-codegen from a
# live database and committed, so consumers need no codegen. A
# migration that changes a column therefore has two halves, and
# only one of them is enforced by anything. The typed-Json columns
# make that worse: `directly_assignable` is `Json`, so the compiler
# cannot notice a payload-shape drift either, and the adapter's
# hand-written parsers are the only thing between a drift and
# silent corruption.
#
# Regenerating into a scratch file rather than over the committed
# one keeps the check side-effect free, so a failure leaves the
# tree exactly as the developer left it.
#
# Requires a database already migrated to HEAD, and DATABASE_URL
# in the environment. The connection string is passed explicitly
# rather than left to the config's `envFile`, which points at the
# repo's gitignored .env: CI has the variables but no such file,
# and kysely-codegen raises on a configured env file it cannot
# find.
set -euo pipefail

: "${DATABASE_URL:?set DATABASE_URL, e.g. 'set -a && . ./.env'}"

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
committed="${root}/packages/kysely/src/schema.ts"
generated="$(mktemp -t tsfga-schema-XXXXXX.ts)"
trap 'rm -f "${generated}"' EXIT

(cd "${root}/packages/kysely" &&
  bunx kysely-codegen --url "${DATABASE_URL}" --out-file "${generated}")

if ! diff -u "${committed}" "${generated}"; then
  echo
  echo "packages/kysely/src/schema.ts does not match the database." >&2
  echo "Run 'bun run db:latest && bun run db:generate' and commit" >&2
  echo "the regenerated file." >&2
  exit 1
fi

echo "schema.ts matches the migrated database."
